name: MonPremierPipeline
on: [push] # Se lance à chaque fois que tu fais un push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Le robot récupère ton code
      - run: echo "Bravo, le pipeline fonctionne !" # Le robot affiche un message
