name: MonPremierPipeline
on: [push] # Se lance à chaque fois que tu fais un push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Le robot récupère ton code
      - run: echo "Bravo, le pipeline fonctionne !" # Le robot affiche un message
            # Installe java 8 sur l'agent
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      # Compile notre application
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
